volumes:
  prometheus_data:
    external: false
  grafana_data:
    external: false

services:
  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.wal-compression'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "7090:9090"
    networks:
      - forecast-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    ports:
      - "7100:9100"
    networks:
      - forecast-network
    restart: unless-stopped

  cadvisor:
    image: ghcr.io/google/cadvisor:0.56.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - "7080:8080"
    networks:
      - forecast-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:12.2.8
    container_name: grafana
    env_file: ./grafana/secret/.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "7000:3000"
    networks:
      - forecast-network
    restart: unless-stopped